<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Nevada Contract - </title>
</head>
<style>
  @page {
              margin: 2cm 2cm 1cm 2cm;
              }
              .page_break { page-break-before: always; }

</style>
<body>
<p style="text-align:center;"><span style="font-size: 20; "><strong>Sunny Landscaping and Pavers Design,  LLC <br> SERVICES AGREEMENT</strong>&nbsp;</span></p>
<p><span style="font-weight: 400;">This SERVICES AGREEMENT (the &ldquo;Agreement&rdquo;) is made as of {{\Carbon\Carbon::parse($data[0]->contract_date)->format('jS \o\f F, Y') }} (the &ldquo;Effective Date&rdquo;) by and between Sunny Landscaping and Pavers Design, LLC, a Landscape company (the &ldquo;Service Provider) and {{$data[0]->company == 1 ? $data[0]->company_name.' c/o '. $data[0]->customer_name:$data[0]->customer_name}}, a {{$data[0]->parties}} (the &ldquo;Client&rdquo;) (collectively referred to herein as the &ldquo;Parties&rdquo;).&nbsp;</span></p>
<p style="text-align:center;" ><span style="font-size: 20;"><strong>RECITALS</strong>&nbsp;</span></p>
<p><span style="font-weight: 400;"><strong>WHEREAS</strong>, the Service Provider is engaged in the business of landscaping and paving, as described in further detail herein (the &ldquo;Landscaping and Pavers Design&rdquo;);&nbsp;</span></p>
<p><span style="font-weight: 400;"><strong>WHEREAS</strong>, the Client wishes to engage the Service Provider to provide the Services, subject to the terms and conditions set forth in this Agreement; and&nbsp;</span></p>
<p><span style="font-weight: 400;"><strong>WHEREAS</strong>, the Service Provider wishes to provide the Services to the Client, subject to such terms and conditions as are set forth in this Agreement.</span></p>
<p style="text-align:center;"><span style="font-weight: 400;"><strong>THE AGREEMENT</strong>&nbsp;</span>
<p><span style="font-weight: 400;"><strong>NOW THEREFORE</strong>, in consideration of the mutual promises and covenants set forth herein, the sufficiency of which are hereby acknowledged, the Service Provider agrees to provide the Services to the Client, and the Client agrees to purchase the Services from the Service Provider, subject to the following terms and conditions:&nbsp;</span></p>
<p style="text-align:center;"><span style="font-weight: 400;"><strong>Article 1 </strong>&nbsp;</span></p>
<p style="text-align:center;"><span style="font-weight: 400;"><strong>Services</strong>&nbsp;</span></p>
<p><span style="font-weight: 400;">1.1 <strong>Primary Services.</strong> In exchange for the Primary Service Fee on the first page of this Agreement, the Service Provider agrees to provide the Client with the Primary Services (the &ldquo;Primary Services&rdquo;), described in detail on the DESCRIPTION OF PRIMARY SERVICES, attached hereto as Exhibit &ldquo;A&rdquo; and incorporated herein by reference.&nbsp;</span></p>
<p style="text-align:center;"><span style="font-weight: 400;"><strong>Article 2 </strong>&nbsp;</span></p>
<p style="text-align:center;"><span style="font-weight: 400;"><strong>Term</strong>&nbsp;</span></p>
<p><span style="font-weight: 400;">2.1 <strong>Term.</strong> The Term of this Agreement shall commence on the Effective Date and shall continue until services are completed, unless either Party terminates the Agreement pursuant to the termination provision set forth below.&nbsp;</span></p>
<p><span style="font-weight: 400;">2.2 <strong>Early Termination.</strong> Either party may terminate this agreement at any time for any reason by providing the other party with written notice of its intent to so terminate. Such termination shall be effective upon delivery of such notice, unless a different date of termination is expressly identified within such notice.&nbsp;</span></p>
<br>
<p><span style="font-weight: 400;">2.3 <strong>Effect of Early Termination.</strong> In the event that either party terminates this Agreement prior to the expiration of the Term, then the following terms and conditions shall apply:&nbsp;</span></p>
<p><span style="font-weight: 400;">2.3.1 The Client shall pay to the Service Provider any monies then owed for Primary Services rendered by the Service Provider prior to and including the date of termination. 2.3.2 The Service Provider shall cease providing any and all services to the Client as of the termination date, except as provided in Section 2.3.3 below. 2.3.3 In the event that the Client has prepaid for any Services, the Service Provider shall continue to provide the Primary Services until such time as the prepaid deposit is entirely exhausted.&nbsp;</span></p>
<p style="text-align:center;"><span style="font-weight: 400;"><strong>Article 3 </strong>&nbsp;</span></p>
<p style="text-align:center;"><span style="font-weight: 400;"><strong>Fees</strong>&nbsp;</span></p>
<p><span style="font-weight: 400;">3.1.1.1 <strong>Primary Service Fee.</strong> In exchange for the Primary Services, the Client shall pay to the Service Provider the sum of set forth on the first page of this Agreement as the &ldquo;Primary Service Fee,&rdquo; to be paid to the Service Provider.&nbsp;</span></p>
<p><span style="font-weight: 400;">3.1.1.2 <strong>Payment Method.</strong> All payments due under this Agreement shall be made by cash, check, credit and debit cards, and Zelle in immediately available funds to a bank account designated by Service Provider. The Primary Service Fee is due upon signing Proposal. <strong>Down Payment</strong> is due on the first day of the job. <strong>Final Balance</strong> is due upon job completion. ________ (Initial)&nbsp;</span></p>
<p><span style="font-weight: 400;">3.1.1.3 <strong>Late Fees and Returned Checks.</strong> In the event that the Primary Service Fee is not paid by the Monthly Due Date, Client shall pay a late fee of $25 plus an additional $10 per day for every day that the Primary Service Fee are past due. In the event that the Client tenders any check to Service Provider that is subsequently returned, the Client shall pay $25 for each check so returned, plus any applicable Late Fees.&nbsp;</span></p>
<p style="text-align:center;"><span style="font-weight: 400;"><strong>Article 4 </strong>&nbsp;</span></p>
<p style="text-align:center;"><span style="font-weight: 400;"><strong>Acknowledgements, Representations, Warranties and Disclaimers</strong>&nbsp;</span></p>
<p><span style="font-weight: 400;">4.1.1.1.1 <strong>No Fiduciary Relationship.</strong> The Service Provider and the Client are completely separate entities and are not fiduciaries or agents of the other in any sense, other than to the extent specifically detailed and described in this Agreement. No act or assistance given by either party to the other according to this Agreement will be construed to alter the relationship.&nbsp;</span></p>
<p><span style="font-weight: 400;">4.1.1.1.2 <strong>Client has Read and Understands Agreement.</strong>  The Client acknowledges that it has read and understands this Agreement and any attachments to this Agreement and that the Service Provider has accorded the Client ample time and opportunity to consult with advisors of Client&rsquo;s own choosing about the potential benefits and risks of entering into this Agreement.&nbsp;</span></p>
<p><span style="font-weight: 400;">4.1.1.1.3 <strong>Punitive and Consequential Damages.</strong>  Under no circumstance shall the Service Provider be liable to the Client or any third party for any amount of punitive damages or consequential damages arising out of or in connection with this Agreement or the exercise by the Client of all or any portion of the rights granted under this Agreement, including, without limitation, any damage, loss, liability, claim, cost, or expense directly or indirectly arising out of or in connection with or otherwise resulting from this Agreement.&nbsp;</span></p>
<p><span style="font-weight: 400;">4.1.1.1.4 <strong>Disclaimer of Warranties.</strong>  EXCEPT AS SPECIFICALLY SET FORTH HEREIN, THE SERVICE PROVIDER MAKES NO FURTHER WARRANTIES TO THE CLIENT, WHETHER EXPRESS OR IMPLIED, AND ALL OTHER WARRANTIES, EITHER EXPRESS OR IMPLIED, ARE HEREBY DISCLAIMED.&nbsp;</span></p>
<p><span style="font-weight: 400;">4.1.1.1.5 Client Acknowledges that <strong>CONCRETE REMOVAL</strong> was calculated considered a 4&rdquo;-thick slab. Whenever the thickness of your patio concrete pad is about 4&rdquo; thick, the following applies: $3.50 sq.ft: Concrete pad above 4&rdquo; without steel mesh or rebar. $35.00 per man-hour: Concrete with steel mesh or rebar. _______ (Initial)&nbsp;</span></p>
<p><span style="font-weight: 400;">4.1.1.1.6 Client Acknowledges that cost for manual <strong>Excavation</strong> takes in consideration the absence of big rocks and is limited to 3&rdquo; depth. If removing bigger rocks or excavation over 3&rdquo; of depth is required, the cost will increase to $3.00/sq.ft _______ (Initial)&nbsp;</span></p>
<p><span style="font-weight: 400;">4.1.1.1.7 Client Acknowledges that motor vehicles on Artificial Grass or any other condition which will expose the Artificial Grass to temperatures exceeding 140 degrees Fahrenheit including damage from sun magnification or reflection from the sun will void warranty. _________ (Initial)&nbsp;</span></p>
<p><span style="font-weight: 400;">4.1.1.1.8 Client Acknowledges that <strong>Natural Stone Acceptance (Travertine)</strong> is a philosophical decision. It entails embracing the organic beauty and variations that nature has given us. No two pieces of natural stone will look the same nor should they. This is the enduring appeal of natural stone and reflects the journey each stone has taken over millions of years before it is quarried from the earth and prepared for your project. Variation is the defining characteristic of natural stone that differentiates it from man made products. As Such, Client understands and acknowledges that any natural stone used is non uniformed and varies piece by piece. _______ (Initial)&nbsp;</span></p>
<p style="text-align:center;"><span style="font-weight: 400;"><strong>Article 5 </strong>&nbsp;</span></p>
<p style="text-align:center;"><span style="font-weight: 400;"><strong>Indemnification and Limitation of Liability</strong>&nbsp;</span></p>
<p><span style="font-weight: 400;">5.1.1.1.1.1 <strong>Indemnification of Client. </strong> Service Provider shall indemnify and hold Client and its directors, officers, employees, agents, consultants and counsel, and its successors and assigns (the &ldquo;Client Indemnitees&rdquo;) harmless from and against any and all liabilities, damages, losses, costs or expenses, including reasonable attorneys&rsquo; and professional fees and other expenses of litigation and arbitration, resulting from a claim, suit or proceeding brought against a Client Indemnitee alleging (I) a breach of Service Provider&rsquo;s representations and warranties set forth herein and (ii) Service Provider&rsquo;s gross negligence or willful misconduct.&nbsp;</span></p>
<p><span style="font-weight: 400;">5.1.1.1.1.2 <strong>Indemnification of Service Provider.</strong> Client shall indemnify and hold Service Provider and its respective directors, officers, employees, agents, consultants and counsel and its successors and assigns (the &ldquo;Service Provider Indemnitees&rdquo;) harmless from and against any and all liabilities, damages, losses, costs or expenses, including reasonable attorneys&rsquo; and professional fees and other expenses of litigation and arbitration, resulting from a claim, suit, or proceeding brought against a Service Provider Indemnitee, arising from or occurring as a result of (i) any and all claims brought by third parties alleging injury or damage in conjunction with, or arising out of the Client&rsquo;s business, (ii) any breach of Client&rsquo;s representations and warranties set forth herein, and (iii) Client&rsquo;s gross negligence or willful misconduct.&nbsp;</span></p>
<div class="page_break"></div>
<p><span style="font-weight: 400;">5.1.1.1.1.3 <strong>Procedure.</strong> Notwithstanding the foregoing, a party under this Agreement which has the obligation to indemnify the other party hereunder (the &ldquo;Indemnifying Party&rdquo;) shall have no obligation to hold an Indemnitee (including a Service Provider Indemnitee or a Client Indemnitee) harmless under this Article for any claims brought by third parties (in each case, a &ldquo;Third-Party Claim&rdquo;) unless the Indemnitee has given the Indemnifying Party commercially reasonable notice of such Third-Party Claim. Failure to give timely notice shall not void the indemnification obligations hereunder unless the Indemnifying Party&rsquo;s ability to defend is materially prejudiced. In the case of a lawsuit, commercially reasonable notice is presumptively within thirty (30) days after the Indemnitee is served with initial pleadings, depending upon when an answer is due in the forum in which the lawsuit is pending. In no event shall the Indemnitee settle or otherwise commit to any liability for which it will seek indemnification from the Indemnifying Party, or would subject the Indemnifying Party to injunctive relief, without express written consent of the Indemnifying Party. In any instance in which the Indemnifying Party reasonably contends that it should not be responsible for a Third-Party Claim, Indemnifying Party shall promptly notify Indemnitee and commence good faith negotiations regarding tender and control of the Third-Party Claim. In the event the parties fail to reach agreement upon the conclusion of such negotiations, Indemnifying Party will continue to handle the Third-Party Claim, and at its option, may initiate litigation against Indemnitee with respect thereto.&nbsp;</span></p>
<p><span style="font-weight: 400;">5.1.1.1.1.4 <strong>Cooperation.</strong> The Indemnitee shall cooperate in the defense of any Third-Party Claim for which indemnification is sought under this Article, but shall be reimbursed for reasonable out of pocket expenses incurred in connection with such cooperation. Although Indemnifying Party shall have control of the defense of any action for which indemnification is sought, Indemnifying Party agrees to comply with the following requirements in connection with the conduct of the defense of any such Third-Party Claim in which the Indemnitee has been named a party: (a) Indemnifying Party shall use all reasonable efforts to promptly provide Indemnitee with copies of all discovery requests which call for the production of documents, testimony or information from Indemnitee as soon as they are available to Indemnifying Party; (b) Indemnifying Party shall provide Indemnitee with copies of all pleadings filed in such case; (c) Indemnifying Party shall consult with Indemnitee regarding the selection of defense counsel; (d) Indemnifying Party or its representatives will keep Indemnitee or its agents informed of all material information pertaining to a Third-Party Claim; (e) Indemnifying Party shall inform Indemnitee of the date of any mediation, arbitration, trial or settlement conference as soon as possible after it receives such information; and (f) Indemnifying Party shall inform Indemnitee of the outcome of any mediation, arbitration, motion, trial or settlement or any other matter from which appeal rights could arise.&nbsp;</span></p>
<p><span style="font-weight: 400;">5.1.1.1.1.5 <strong>Participation.</strong> Indemnitee, at its own expense, shall have the right, but not the obligation, to participate as it deems necessary in the handling, adjustment, or defense of any Third-Party Claim for which Indemnifying Party is indemnifying, defending, and holding Indemnitee harmless. Should Indemnitee so elect, its obligations under this Article to cooperate in the defense of any such Third-Party Claim shall not be altered. If Indemnitee reasonably determines that a defense or defenses are available to it that are not available to Indemnifying Party and raising such defense or defenses would create a material conflict of interest for the counsel defending the Third-Party Claim, the Indemnitee shall notify Indemnifying Party and the parties shall commence good faith negotiations regarding raising such defense or defenses. In the event the parties fail to reach agreement upon the conclusion of such negotiations, Indemnitee shall notify Indemnifying Party to, and Indemnifying Party shall, after consulting with Indemnitee regarding the selection of defense counsel, retain separate counsel reasonably acceptable to Indemnifying Party for the purpose of raising these defenses, at Indemnifying Party&rsquo;s reasonable expense, and at its option may initiate litigation against Indemnitee with respect thereto.&nbsp;</span></p>
<div class="page_break"></div>

<p><span style="font-weight: 400;">5.1.1.1.1.6 <strong>Consultation.</strong> The Indemnifying Party may not effect any compromise or settlement of a Third-Party Claim that would result in the admission of any liability by Indemnitee, any financial liability on the part of Indemnitee, or would subject Indemnitee to injunctive relief without first obtaining Indemnitee&rsquo;s prior written consent, and Indemnitee shall have no liability with respect to any such compromise or settlement of the Third-Party Claim effected without its consent. In view of the potential impact of the Indemnifying Party&rsquo;s defense and disposition of claims pursuant to this Article on the other party&rsquo;s business, operations, and marketing and sales of products, the Indemnifying Party shall at all times consult with and keep the other party apprised of the status of all claims and of all proposed strategies and decisions with respect to the defense and disposition thereof.&nbsp;</span></p>
<p><span style="font-weight: 400;">5.1.1.1.1.7 <strong>Exclusion of Damages.</strong> In no event shall either party be liable under this Agreement to the other party for any incidental, consequential, special, punitive, indirect, or exemplary damages, including damages from loss of profits or opportunities, even if advised of the possibility of such damages.&nbsp;</span></p>
<p style="text-align:center;"><span style="font-weight: 400;"><strong>Article 6 </strong>&nbsp;</span></p>
<p style="text-align:center;"><span style="font-weight: 400;"><strong>Miscellaneous</strong>&nbsp;</span></p>
<p><span style="font-weight: 400;">6.1.1.1.1.1.1 <strong>Notices.</strong> Any and all notices that either party hereto desires or is required to give to the other party pursuant to this Agreement shall be in writing and delivered in person, sent by overnight courier (with confirmation of delivery) or sent by express, certified or priority U.S. mail postage prepaid (return receipt requested), addressed as follows:&nbsp;</span></p>
<p><span style="font-weight: 400;">To Client: &nbsp;</span></p>
<p><span style="font-weight: 400;line-height: 10px;">{{$data[0]->customer_name}}&nbsp;</span></p>
<p><span style="font-weight: 400;line-height: 0px;">{{ $data[0]->address}} {{ $data[0]->city_name}}, {{ $data[0]->state}} {{ $data[0]->zipcode}}&nbsp;</span></p>
<p><span style="font-weight: 400;line-height: 40px;">To Service Provider:&nbsp;</span></p>
<p><span style="font-weight: 400;line-height: 0px;">Sunny Landscaping and Pavers Design, LLC&nbsp;</span></p>
<p><span style="font-weight: 400;">3183 Ramrod Street Las Vegas, NV 89108&nbsp;</span></p>
<br>
<br>
<p><span style="font-weight: 400;">6.1.1.1.1.1.2 </span><span style="font-weight: 400;"><strong>Arbitration.</strong> </span><span style="font-weight: 400;">Except as otherwise set forth herein, any dispute, difference or question relating to or arising among any of the parties concerning the construction, meaning, effect or implementation of this Agreement or the rights or obligations of any party hereof will be submitted to, and settled by arbitration by a single arbitrator chosen by the corresponding Regional Office of the American Arbitration Association in accordance with the Commercial Rules of the American Arbitration Association. The Parties shall submit briefs of no more than 10 pages and the arbitration hearing shall be limited to two (2) days maximum. The arbitrator shall apply Nevada law. Unless otherwise agreed by the parties, arbitration will take place in Las Vegas, Nevada, U.S.A. Any court having jurisdiction over the matter may enter judgment on the award of the arbitrator. Service of a petition to confirm the arbitration award may be made by regular mail or by commercial express mail, to the attorney for the party or, if unrepresented, to the party at the last known business address.&nbsp;</span></p>
<div class="page_break"></div>
<p><span style="font-weight: 400;">6.1.1.1.1.1.3 <strong> Governing Law. </strong> This Agreement shall be construed and interpreted in accordance with and shall be governed and enforced in all respects according to the laws of the State of Nevada, without giving effect to conflicts of laws principles. The Parties each agree to the exclusive jurisdiction (aside from the terms of the Arbitration listed in 6.1.1.1.1.1.2 of any state or federal court within the County of Clark, State of Nevada, with respect to any claim or cause of action arising under or relating to this Agreement, and waive personal service of any and all process upon it and consent that all service of process be made by overnight courier (with confirmation of delivery), certified, registered, or priority U.S. mail (return receipt requested), directed to it at its address as set forth hereunder and service so made shall be deemed to be completed when received. The parties each waive any objection based on forum nonconveniens and waive any objection to venue of any action instituted hereunder.&nbsp;&nbsp;</span></p>
<p><span style="font-weight: 400;">6.1.1.1.1.1.4 <strong> Severability.</strong> If any term or provision of this Agreement, or the application thereof to any person or circumstances shall, to any extent, be invalid or unenforceable, the remainder of this Agreement, or the application of such term or provision to persons or circumstances other than those as to which it is held invalid or unenforceable, shall not be affected thereby; each term and provision of this Agreement shall be valid and enforced to the fullest extent permitted by law.&nbsp;</span></p>
<p><span style="font-weight: 400;">6.1.1.1.1.1.5 <strong> Non-Waiver. </strong>Acceptance of the Primary Service Fee by Service Provider shall not be deemed a waiver by Service Provider of any prior breach of this Agreement. The failure of Service Provider in any case to enforce or insist upon the strict performance of any provision of this Agreement shall not prevent a subsequent act, which would have originally constituted a violation of this Agreement, from having all the force and effect of an original violation.&nbsp;</span></p>
<p><span style="font-weight: 400;">6.1.1.1.1.1.6 <strong> Amendment.</strong> This Agreement may be modified or amended only pursuant to a writing executed by both parties.&nbsp;</span></p>
<p><span style="font-weight: 400;">6.1.1.1.1.1.7 <strong> Assignment.</strong> Any party may make a complete and undivided assignment of this Agreement, together with all of its rights and obligations hereunder, to a single successor of the business to which this Agreement pertains, where such successor agrees to the terms hereof, and that successor may in the same manner assign this agreement to its own successor on the same terms and conditions. Any other assignment of a party or successor shall be void unless prior express written consent of the other parties hereto is obtained.&nbsp;</span></p>
<p><span style="font-weight: 400;">6.1.1.1.1.1.8 <strong>Independent Contractors.</strong> Nothing contained in this Agreement is intended, or is to be construed, to create a legal relationship between Client and Service Provider as partners. No party hereto shall have any express or implied right or authority to assume or create any obligations on behalf of or in the name of any other party or to bind any other party to any contract, agreement, or undertaking with any third party.&nbsp;</span></p>
<p><span style="font-weight: 400;">6.1.1.1.1.1.9 <strong>Attorney&rsquo;s Fees.</strong> Each party hereto shall bear its own professional fees and expenses incurred by such party in connection with, relating to or arising out of the execution, delivery, and performance of this Agreement and the consummation of the transactions contemplated hereby; provided however, in the event any dispute between the parties should result in litigation, the prevailing party shall be reimbursed for all costs incurred in connection with such litigation, including, without limitation, reasonable attorneys&rsquo; fees and costs.&nbsp;</span></p>
<p><span style="font-weight: 400;">6.1.1.1.1.1.10 <strong>Punitive and Consequential Damages.</strong> Under no circumstance shall Service Provider be liable to the Client or any third party for any amount of punitive damages or consequential damages arising out of or in connection with this Agreement or the exercise by Client of all or any portion of the rights granted under this Agreement. Client hereby expressly waives any right to punitive or consequential damages resulting from any claim arising out of this Agreement.&nbsp;</span></p>
<p><span style="font-weight: 400;">6.1.1.1.1.1.11 <strong>Headings.</strong> The paragraph headings to this Agreement are for convenience and reference only; and the words contained therein shall in no way be held to explain, modify, amplify, or aid in the interpretation, construction or meaning of the provisions of this Agreement.&nbsp;</span></p>
<p><span style="font-weight: 400;">6.1.1.1.1.1.12 <strong>Interpretation.</strong> Plural shall be substituted for the singular form and vice versa in any place or places herein in which the context requires such substitution or substitutions. Each party to this Agreement represents that it has read and understood each provision of this Agreement and has discussed this Agreement with legal counsel or has been advised to and has been provided the opportunity to discuss this Agreement with legal counsel. The parties hereto therefore stipulate and agree that the rule of construction to the effect that any ambiguities are to be or may be resolved against the drafting party shall not be employed in the interpretation of this Agreement to favor any party against another.&nbsp;&nbsp;</span></p>
<p><span style="font-weight: 400;">6.1.1.1.1.1.13 <strong>Entire Agreement.</strong> This Agreement, when properly executed by the parties or their authorized agents, shall constitute the only agreement among the parties with respect to the subject matter stated herein and shall supersede all prior agreements between the parties, whether written or oral. This Agreement may be amended only by a writing executed by all Parties hereto.&nbsp;</span></p>
<p><span style="font-weight: 400;">6.1.1.1.1.1.14 <strong>Time.</strong> Time is of the essence of this Agreement and all terms and conditions hereof.&nbsp;</span></p>
<p><span style="font-weight: 400;">6.1.1.1.1.1.15 <strong>Counterparts.</strong> This Agreement may be executed in counterparts and all of such counterparts, taken together, shall be deemed part of one instrument. Facsimile and/or electronically transmitted signatures shall be binding for purposes of this Agreement.&nbsp;</span></p>
<p><span style="font-weight: 400;">6.1.1.1.1.1.16 <strong>Client has Read and Understands this Agreement.</strong> The Client hereby represents and warrants that Client has read this Agreement in its entirety and fully understands the contents hereof. The Client further represents that that the Service Provider provided the Client with an opportunity to have this Agreement reviewed by an attorney of the Client&rsquo;s choosing.&nbsp;</span></p>
<p><span style="font-weight: 400;">This <strong>SERVICES AGREEMENT</strong> is hereby executed and acknowledged by the parties as of the date and year set forth below.&nbsp;</span></p>
<p><span style="font-weight: 400;">CLIENT&nbsp;</span></p>
<p><span style="font-weight: 400;">________________________________________  &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;                   __________________ &nbsp;</span></p>
<p style="line-height: 0px;"><span style="font-weight: 400;">Signature - {{$data[0]->customer_name}}</span><span style="margin-left: 370px"> Date</span></p>
<br>
<p><span style="font-weight: 400;">SERVICE PROVIDER&nbsp;</span></p>
<div style="text-align: center">
  <img  style="height: 35%; width: 35%; position: absolute; margin-top: -50px" src="https://i.ibb.co/4jY1dHg/signature.png" data-holder-rendered="true" />       
</div>
<p><span style="font-weight: 400;">________________________________________  &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;                   <span style="text-decoration: underline">{{\Carbon\Carbon::parse($data[0]->contract_date)->format('jS \o\f F, Y') }} </span> &nbsp;</span></p>
<p style="line-height: 2px;"><span style="font-weight: 400;">Glaucia Alves  <span style="margin-left: 410px"> Date</span></p></span></p>
<p style="line-height: 10px;"><span style="font-weight: 400;">Managing Member </span></p>
<p style="line-height: 10px;"><span style="font-weight: 400;">Sunny Landscaping and Pavers Design,  LLC </span></p> 
</body>
</html>